version: '3.8'

services:
  # ==========================================
  # APLICAÃ‡AO (API)
  # ==========================================
  api:
    build: .
    container_name: gestao_artistas_api
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy  # Espera o banco estar 100%
      minio:
        condition: service_started
    environment:
      # ESSA LINHA SOBRESCREVE O APPLICATION.PROPERTIES
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/gestao_artistas_api_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET_NAME: capas-albuns

  # ==========================================
  # BANCO DE DADOS (Com Healthcheck)
  # ==========================================
  db:
    image: postgres:15-alpine
    container_name: gestao_artistas_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gestao_artistas_api_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      # NOME CORRETO NO TESTE DE SAUDE
      test: ["CMD-SHELL", "pg_isready -U user -d gestao_artistas_api_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # ==========================================
  # STORAGE S3 (MinIO)
  # ==========================================
  minio:
    image: minio/minio
    container_name: gestao_artistas_minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  # ==========================================
  # CONFIGURADOR (Cria bucket automatico)
  # ==========================================
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/capas-albuns;
      /usr/bin/mc anonymous set public myminio/capas-albuns;
      exit 0;
      "

volumes:
  postgres_data:
  minio_data: